# Generated by Django 3.0.6 on 2020-05-20 13:07

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_custom_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='custom_url',
            field=models.CharField(default='None', error_messages={'invalid': 'Invalid url', 'unique': 'A user with that username already exists.'}, help_text='Required. 50 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
